// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package tutorial

import (
	"github.com/podhmo/nullable"
)

type Author struct {
	ID   int64                 `db:"id" json:"id"`
	Name string                `db:"name" json:"name"`
	Bio  nullable.Type[string] `db:"bio" json:"bio"`
}
